name: bookstore 
on: push 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v3

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7

            - name: Setup Node.js
              uses: actions/setup-node@v2
        #   with:
        #     node-version: 14

            # - name: Install Yarn
            #   run: npm install -g yarn

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            # - name: Run 
            #   run: dotnet run 
              #having isshu in this command 

            - name: Test
              run: dotnet test --no-restore --verbosity normal
              

    # test:
    #     needs: build
    #     runs-on: ububtu-latest
    #     steps:
    #         #steps for testing the page

    # deplpy: 
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Build the docker image
    #           run: docker build -t dotnet-application
            
    #         - name: Push image to ECR
    #           run: docker login 
    #           run: docker push xyz




